python3: can't open file '/Users/mac/work/gensyn/rl-swarm/ops/monitoring/ops/monitoring/auto_restart_monitor.py': [Errno 2] No such file or directory
